### ISSUE TITLE
@extend cannot be used from within @media

### ISSUE THREAD

**Issue by blainehansen** [zessx/sass-flexbox#3]
Since almost the entire library uses `@extend` from within mixins, the mixins fail when called from within media directives.

I'd like to suggest a reversal of the current strategy, where the mixins call `@extend`. Instead, the `@extend`s should call the mixins.

So from this:

```scss
%display-flex {
    display: -webkit-box;
    display: -moz-box;
    display: -webkit-flexbox;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
}
@mixin display-flex() {
    @extend %display-flex;
}
```

to this:

```scss
@mixin display-flex() {
    display: -webkit-box;
    display: -moz-box;
    display: -webkit-flexbox;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
}
%display-flex {
    @include display-flex();
}
```
